apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapr-grpc-service-template
  labels:
    app: dapr-grpc-service-template
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dapr-grpc-service-template
  template:
    metadata:
      labels:
        app: dapr-grpc-service-template
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "dapr-grpc-service-template"
        dapr.io/port: "50001"
        dapr.io/protocol: "grpc"
        dapr.io/config: "tracing"
        dapr.io/log-level: "debug"
    spec:
      containers:
      - name: user-container
        image: mchmarny/dapr-grpc-service-template:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 50001
        env:
        - name: PORT
          value: "50001"
        - name: DAPR_HTTP_PORT
          value: "3500"